### ISSUE TITLE
Does not receive group messages

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/connector-ciscospark#1]
It appears that despite the bot being in multiple rooms the webhook only sends direct messages.

**Comment by sgreszcz** [comment]
Yes, it seems that Spark treats 1:1 spaces with the bot different than a multi-party space with the bot.  Personally I'd prefer the bot to be bound to a given room (if that is possible) to contain all chatops for traceability. 
 I'll look more into this issue and test. 
https://communities.cisco.com/community/developer/spark/blog/2017/06/13/building-a-more-secure-bot
