### ISSUE TITLE
Fix some bugs to cisco spark and change the project name

### ISSUE THREAD

**Issue by wilelm123** [opsdroid/connector-ciscospark#13]
Hi opsdroid team, cisco has renamed ciscospark to webexteams, and I found this repo not work with the latest version of opsdroid(0.14.1), so I fix some bugs and it work properly now, can you create a new project named webexteams and then I push the code to the new repo or I still push the bug fix to this repo

**Comment by jacobtomlinson** [comment]
Awesome thanks! Looking forward to reviewing your PR.
